In [2]:
import tensorflow as tf

In [9]:
(x_train,y_train),(x_test,y_test)=tf.keras.datasets.mnist.load_data()

In [10]:
x_train.shape

(60000, 28, 28)

In [11]:
x_test.shape

(10000, 28, 28)

In [12]:
x_train = x_train.reshape(x_train.shape[0],28,28,1)
x_test = x_test.reshape(x_test.shape[0],28,28,1)
input_shape = (28,28,1)

In [13]:
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')

In [14]:
x_train /= 255
x_test /= 255

In [15]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D, Dropout, Flatten, MaxPooling2D
model = Sequential()
model.add(Conv2D(28, kernel_size=(3,3), input_shape=input_shape))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(128, activation=tf.nn.relu))
model.add(Dropout(0.2))
model.add(Dense(10,activation=tf.nn.softmax))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [16]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])
model.fit(x=x_train,y=y_train,epochs=10)

Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 45s 23ms/step - accuracy: 0.8871 - loss: 0.3779
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 82s 23ms/step - accuracy: 0.9730 - loss: 0.0875
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 42s 23ms/step - accuracy: 0.9810 - loss: 0.0601
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 82s 22ms/step - accuracy: 0.9859 - loss: 0.0435
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 83s 23ms/step - accuracy: 0.9894 - loss: 0.0317
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 82s 23ms/step - accuracy: 0.9901 - loss: 0.0288
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 81s 23ms/step - accuracy: 0.9926 - loss: 0.0231
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 81s 22ms/step - accuracy: 0.9938 - loss: 0.0190
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 42s 22ms/step - accuracy: 0.9935 - loss: 0.0182
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 81s 22ms/step - accuracy: 0.9949 - loss: 0.0165


In [17]:
model.evaluate(x_test,y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9797 - loss: 0.0927


[0.07746976613998413, 0.9825000166893005]

In [18]:
y_pred = model.predict(x_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step


In [20]:
y_pred

array([[1.46551797e-13, 8.55432253e-11, 5.10862359e-11, ...,
        9.99999940e-01, 1.20233357e-09, 1.89542840e-10],
       [6.07131678e-10, 5.61280501e-07, 9.99999344e-01, ...,
        4.21063932e-21, 1.74060517e-15, 1.28215880e-24],
       [2.59192090e-09, 9.99999702e-01, 3.11636633e-10, ...,
        2.86211321e-09, 3.35394041e-08, 6.88149895e-15],
       ...,
       [8.04765098e-23, 8.45351163e-16, 9.50982336e-18, ...,
        7.47246431e-11, 1.46076066e-12, 1.29906030e-10],
       [2.51628735e-18, 6.22095311e-13, 1.12099956e-19, ...,
        2.00151471e-15, 5.88342573e-07, 7.67321429e-20],
       [3.16328562e-15, 1.03395313e-16, 1.17167387e-12, ...,
        2.28313901e-20, 1.28532276e-13, 1.10219757e-21]], dtype=float32)

In [21]:
import numpy as np
y_predicts = np.argmax(y_pred,axis=1)

In [23]:
y_predicts

array([7, 2, 1, ..., 4, 5, 6])

In [24]:
y_test

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [25]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_predicts))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99       980
           1       0.99      0.99      0.99      1135
           2       0.98      0.98      0.98      1032
           3       0.99      0.97      0.98      1010
           4       0.98      0.99      0.98       982
           5       0.97      0.98      0.98       892
           6       0.98      0.98      0.98       958
           7       0.98      0.99      0.98      1028
           8       0.98      0.98      0.98       974
           9       0.99      0.96      0.97      1009

    accuracy                           0.98     10000
   macro avg       0.98      0.98      0.98     10000
weighted avg       0.98      0.98      0.98     10000

